ink_home:
    resource: "@InkHomeBundle/Resources/config/routing.yml"
    prefix:   /

ink_user:
    resource: "@InkUserBundle/Resources/config/routing.yml"
    prefix:   /

ink_general:
    resource: "@InkGeneralBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"